spring:
    datasource:
      url: jdbc:mysql://localhost:3306/hollow_test
      username: root
      password: <your_password>
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
